version: '3.8'
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://dind:2375
  dind:
    build:
      context: ./dind
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - dind_storage:/var/lib/docker
volumes:
  jenkins_home:
  dind_storage:
